CREATE TABLE SubjectTeacher(
	ID INTEGER CONSTRAINT pk_SubjectTeacher PRIMARY KEY,
	IDSUBJECT INTEGER,
	IDTEACHER INTEGER,
	CONSTRAINT fk_sSubjectTeacher FOREIGN KEY(IDSUBJECT) REFERENCES SUBJECT(ID),
	CONSTRAINT fk_tSubjectTeacher FOREIGN KEY(IDTEACHER) REFERENCES TEACHER(ID)
);